/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// RuleGroupSingle struct for RuleGroupSingle
type RuleGroupSingle struct {
	Data                 RuleGroupRead `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _RuleGroupSingle RuleGroupSingle

// NewRuleGroupSingle instantiates a new RuleGroupSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleGroupSingle(data RuleGroupRead) *RuleGroupSingle {
	this := RuleGroupSingle{}
	this.Data = data
	return &this
}

// NewRuleGroupSingleWithDefaults instantiates a new RuleGroupSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleGroupSingleWithDefaults() *RuleGroupSingle {
	this := RuleGroupSingle{}
	return &this
}

// GetData returns the Data field value
func (o *RuleGroupSingle) GetData() RuleGroupRead {
	if o == nil {
		var ret RuleGroupRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RuleGroupSingle) GetDataOk() (*RuleGroupRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RuleGroupSingle) SetData(v RuleGroupRead) {
	o.Data = v
}

func (o RuleGroupSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *RuleGroupSingle) UnmarshalJSON(bytes []byte) (err error) {
	varRuleGroupSingle := _RuleGroupSingle{}

	if err = json.Unmarshal(bytes, &varRuleGroupSingle); err == nil {
		*o = RuleGroupSingle(varRuleGroupSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRuleGroupSingle struct {
	value *RuleGroupSingle
	isSet bool
}

func (v NullableRuleGroupSingle) Get() *RuleGroupSingle {
	return v.value
}

func (v *NullableRuleGroupSingle) Set(val *RuleGroupSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleGroupSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleGroupSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleGroupSingle(val *RuleGroupSingle) *NullableRuleGroupSingle {
	return &NullableRuleGroupSingle{value: val, isSet: true}
}

func (v NullableRuleGroupSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleGroupSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
