/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// RecurrenceSingle struct for RecurrenceSingle
type RecurrenceSingle struct {
	Data                 RecurrenceRead `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _RecurrenceSingle RecurrenceSingle

// NewRecurrenceSingle instantiates a new RecurrenceSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurrenceSingle(data RecurrenceRead) *RecurrenceSingle {
	this := RecurrenceSingle{}
	this.Data = data
	return &this
}

// NewRecurrenceSingleWithDefaults instantiates a new RecurrenceSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurrenceSingleWithDefaults() *RecurrenceSingle {
	this := RecurrenceSingle{}
	return &this
}

// GetData returns the Data field value
func (o *RecurrenceSingle) GetData() RecurrenceRead {
	if o == nil {
		var ret RecurrenceRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RecurrenceSingle) GetDataOk() (*RecurrenceRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RecurrenceSingle) SetData(v RecurrenceRead) {
	o.Data = v
}

func (o RecurrenceSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *RecurrenceSingle) UnmarshalJSON(bytes []byte) (err error) {
	varRecurrenceSingle := _RecurrenceSingle{}

	if err = json.Unmarshal(bytes, &varRecurrenceSingle); err == nil {
		*o = RecurrenceSingle(varRecurrenceSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRecurrenceSingle struct {
	value *RecurrenceSingle
	isSet bool
}

func (v NullableRecurrenceSingle) Get() *RecurrenceSingle {
	return v.value
}

func (v *NullableRecurrenceSingle) Set(val *RecurrenceSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurrenceSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurrenceSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurrenceSingle(val *RecurrenceSingle) *NullableRecurrenceSingle {
	return &NullableRecurrenceSingle{value: val, isSet: true}
}

func (v NullableRecurrenceSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurrenceSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
