/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// BudgetLimitSingle struct for BudgetLimitSingle
type BudgetLimitSingle struct {
	Data                 BudgetLimitRead `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _BudgetLimitSingle BudgetLimitSingle

// NewBudgetLimitSingle instantiates a new BudgetLimitSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBudgetLimitSingle(data BudgetLimitRead) *BudgetLimitSingle {
	this := BudgetLimitSingle{}
	this.Data = data
	return &this
}

// NewBudgetLimitSingleWithDefaults instantiates a new BudgetLimitSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBudgetLimitSingleWithDefaults() *BudgetLimitSingle {
	this := BudgetLimitSingle{}
	return &this
}

// GetData returns the Data field value
func (o *BudgetLimitSingle) GetData() BudgetLimitRead {
	if o == nil {
		var ret BudgetLimitRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BudgetLimitSingle) GetDataOk() (*BudgetLimitRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BudgetLimitSingle) SetData(v BudgetLimitRead) {
	o.Data = v
}

func (o BudgetLimitSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BudgetLimitSingle) UnmarshalJSON(bytes []byte) (err error) {
	varBudgetLimitSingle := _BudgetLimitSingle{}

	if err = json.Unmarshal(bytes, &varBudgetLimitSingle); err == nil {
		*o = BudgetLimitSingle(varBudgetLimitSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBudgetLimitSingle struct {
	value *BudgetLimitSingle
	isSet bool
}

func (v NullableBudgetLimitSingle) Get() *BudgetLimitSingle {
	return v.value
}

func (v *NullableBudgetLimitSingle) Set(val *BudgetLimitSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableBudgetLimitSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableBudgetLimitSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBudgetLimitSingle(val *BudgetLimitSingle) *NullableBudgetLimitSingle {
	return &NullableBudgetLimitSingle{value: val, isSet: true}
}

func (v NullableBudgetLimitSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBudgetLimitSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
