/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// TransactionSingle struct for TransactionSingle
type TransactionSingle struct {
	Data                 TransactionRead `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _TransactionSingle TransactionSingle

// NewTransactionSingle instantiates a new TransactionSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionSingle(data TransactionRead) *TransactionSingle {
	this := TransactionSingle{}
	this.Data = data
	return &this
}

// NewTransactionSingleWithDefaults instantiates a new TransactionSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionSingleWithDefaults() *TransactionSingle {
	this := TransactionSingle{}
	return &this
}

// GetData returns the Data field value
func (o *TransactionSingle) GetData() TransactionRead {
	if o == nil {
		var ret TransactionRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *TransactionSingle) GetDataOk() (*TransactionRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *TransactionSingle) SetData(v TransactionRead) {
	o.Data = v
}

func (o TransactionSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *TransactionSingle) UnmarshalJSON(bytes []byte) (err error) {
	varTransactionSingle := _TransactionSingle{}

	if err = json.Unmarshal(bytes, &varTransactionSingle); err == nil {
		*o = TransactionSingle(varTransactionSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTransactionSingle struct {
	value *TransactionSingle
	isSet bool
}

func (v NullableTransactionSingle) Get() *TransactionSingle {
	return v.value
}

func (v *NullableTransactionSingle) Set(val *TransactionSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionSingle(val *TransactionSingle) *NullableTransactionSingle {
	return &NullableTransactionSingle{value: val, isSet: true}
}

func (v NullableTransactionSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
