/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// AttachmentSingle struct for AttachmentSingle
type AttachmentSingle struct {
	Data                 AttachmentRead `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _AttachmentSingle AttachmentSingle

// NewAttachmentSingle instantiates a new AttachmentSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachmentSingle(data AttachmentRead) *AttachmentSingle {
	this := AttachmentSingle{}
	this.Data = data
	return &this
}

// NewAttachmentSingleWithDefaults instantiates a new AttachmentSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentSingleWithDefaults() *AttachmentSingle {
	this := AttachmentSingle{}
	return &this
}

// GetData returns the Data field value
func (o *AttachmentSingle) GetData() AttachmentRead {
	if o == nil {
		var ret AttachmentRead
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AttachmentSingle) GetDataOk() (*AttachmentRead, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AttachmentSingle) SetData(v AttachmentRead) {
	o.Data = v
}

func (o AttachmentSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *AttachmentSingle) UnmarshalJSON(bytes []byte) (err error) {
	varAttachmentSingle := _AttachmentSingle{}

	if err = json.Unmarshal(bytes, &varAttachmentSingle); err == nil {
		*o = AttachmentSingle(varAttachmentSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAttachmentSingle struct {
	value *AttachmentSingle
	isSet bool
}

func (v NullableAttachmentSingle) Get() *AttachmentSingle {
	return v.value
}

func (v *NullableAttachmentSingle) Set(val *AttachmentSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachmentSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachmentSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachmentSingle(val *AttachmentSingle) *NullableAttachmentSingle {
	return &NullableAttachmentSingle{value: val, isSet: true}
}

func (v NullableAttachmentSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachmentSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
