/*
Firefly III API v1.5.4

This is the documentation of the Firefly III API. You can find accompanying documentation on the website of Firefly III itself (see below). Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. This file was last generated on 2021-09-25T14:21:28+00:00

API version: 1.5.4
Contact: james@firefly-iii.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gofirefly

import (
	"encoding/json"
)

// ConfigurationSingle struct for ConfigurationSingle
type ConfigurationSingle struct {
	Data                 APIConfiguration `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ConfigurationSingle ConfigurationSingle

// NewConfigurationSingle instantiates a new ConfigurationSingle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigurationSingle(data APIConfiguration) *ConfigurationSingle {
	this := ConfigurationSingle{}
	this.Data = data
	return &this
}

// NewConfigurationSingleWithDefaults instantiates a new ConfigurationSingle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigurationSingleWithDefaults() *ConfigurationSingle {
	this := ConfigurationSingle{}
	return &this
}

// GetData returns the Data field value
func (o *ConfigurationSingle) GetData() APIConfiguration {
	if o == nil {
		var ret APIConfiguration
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfigurationSingle) GetDataOk() (*APIConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConfigurationSingle) SetData(v APIConfiguration) {
	o.Data = v
}

func (o ConfigurationSingle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ConfigurationSingle) UnmarshalJSON(bytes []byte) (err error) {
	varConfigurationSingle := _ConfigurationSingle{}

	if err = json.Unmarshal(bytes, &varConfigurationSingle); err == nil {
		*o = ConfigurationSingle(varConfigurationSingle)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigurationSingle struct {
	value *ConfigurationSingle
	isSet bool
}

func (v NullableConfigurationSingle) Get() *ConfigurationSingle {
	return v.value
}

func (v *NullableConfigurationSingle) Set(val *ConfigurationSingle) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationSingle) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationSingle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationSingle(val *ConfigurationSingle) *NullableConfigurationSingle {
	return &NullableConfigurationSingle{value: val, isSet: true}
}

func (v NullableConfigurationSingle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationSingle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
